package com.faqiy.kokikreatif

object DataResep{
    private val namaResep = arrayOf(
        "Nasi Goreng Cup",
        "Sempol Ayam",
        "Martabak Mini",
        "Kebeb",
        "Macaroni Schotel",
        "Telor Gulung",
        "Cilok",
        "Dumpling Ayam",
        "Samose",
        "Leker Pisang Keju",
        "Takoyaki",
        "Donat Sate",
        "Kue Cubit",
        "Tahu Walik Aci",
        "Oreo Goreng",

    )

    private val bahanResep = arrayOf(
        "-1 centong nasi\n -5 batang sawi\n -1 butir telur\n -1 siung bawang putih\n -1 sendok teh kecap asin\n -1 sendok teh minyak wijen\n -1 sendok teh kecap asin\n -kecap manis secukupnya\n -kol secukupnya -daun bawang secukupnya\n -1/2 sendok teh garam\n -1/2 sendok teh lada",
        "-1 kilogram dada ayam fillet\n -1/2 kilogram tepung terigu\n -1 kilogram tepung kanji\n -4 butir telur\n -5 sendok makan garam\n -6 sachet kaldu bubuk\n -5 sachet lada bubuk\n -20 siung bawang putih\n -4 batang daun bawang\n -10 sendok makan bawang goreng\n -8 sendok makan bawang putih\n -1 liter air mendidih",
        "-1 butir telur\n -1 sendok teh fermipan\n -250 gram tepung terigu\n -1 sendok teh baking powder\n -3 sendok makan gula pasir\n -mentega secukupnya\n -taburan coklat secukupnya\n -taburan keju secukupnya",
        "-250 gram daging ayam\n -10 sosis sapi\n -selada\n -saus tomat secukupnya\n -mayonaise secukupnya",
        "-200 gram makaroni rebus\n -50 gram keju parut\n -2 buah sosis sapi, iris serong\n -2 buah telur, kocok lepas\n -1 buah paprika, iris dadu\n -1 buah bawang bombai\n -2 siung bawang putih\n -gula secukupnya\n -garam secukupnya\n -kaldu bubuk secukupnya,\n Bahan untuk saus putih\n -500 gram susu cair\n -2 sendok makan mentega\n -2 sendok makan tepung terigu\n -50 gram keju parut\n -gula secukupnya\n -garam secukupnya",
        "-2 butir telur\n -1/4 sendok teh kaldu bubul\n -1/4 sendok teh garam\n -1/4 sendok teh lada\n -Minyak goreng\n -Tusuk sate",
        "-8 sendok makan tepung tapioka\n -8 sendok makan tepung kanji\n -1/4 sendok teh kaldu bubuk\n -2 siung bawang putih\n -10 butir merica\n -1/2 sendok teh garam\n -1 batang daun bawang",
        "-500 gram daging ayam\n -1/2 buah wortel, cincang\n -sawi putih cincang\n -jamur tiram cincang\n -1 butir telur\n -1 sendok makan saus tiram\n -1 sendok makan wijen\n -1 sendok teh kecap asin\n -1 sendok teh merica bubuk\n -1 sendok teh garam\n -1 sendok teh gula\n -3 siung bawang putih, cincang halus,",
        "-Kulit lumpia secukupnya\n -1 buah kentang\n -1 buah wortel\n -Daging ayam cincang secukupnya\n -1 siung bawang putih\n -2 siung bawang merah\n -Garam secukupnya\n -3 sendok makan bubuk kari\n -3 buah cabe rawit\n -Daun seledri cincang\n -garam secukupnya\n -gula secukupnya",
        "-Irisan pisang secukupnya\n -Taburan coklat secukupnya\n -Keju parut secukupnya\n -25 gram tepung tapioka\n -75 gram tepung terigu\n -50 gram tepung beras\n -200 gram susu cair / bisa juga dengan air biasa\n -1 butir telur\n -1/2 sendok teh vanili\n -1/2 sendok teh soda kue\n -1/2 sendoh teh garam\n -2 sendok makan gula pasir",
        "-1/2 kilogram tepung terigu\n -1/2 sendok teh baking powder\n -1 butir telur\n -Daun bawang cincang\n -Sosis secukupnya\n -Ayam rebus secukupnya\n -Mayonaise secukupnya\n -Saus tomat secukupnya\n -Garam secukupnya\n -Kaldu bubuk secukupnya",
        "-250 gram tepung terigu\n -1 sendok teh fermipan\n -40 gram margarin\n -2 sendok makan susu bubuk\n -4 sendok makan gula pasir\n -1 sendok teh garam",
        "-3 butir telur\n - 150 gr gula pasir\n - 80 gr margarin\n - 118 ml air\n - 275 gr tepung terigu\n - 1/2 sdt garam\n - 1 bungkus vanili\n - 1 sdt baking powder\n - 1 sdt bubuk matcha\n - 3 sdt bubuk taro\n - 2-5 sdt pewarna merah tuang\n - 1 sdt coklat bubuk\n - 1/2 sdt cuka apel",
        "-10 buah tahu pong atau putih yang telah digoreng\n - 2 sdm tepung terigu\n - 10 sdm tepung aci atau tepung tapioka\n - 1 batang daun bawang segar\n - 2 sdm tepung terigu\n - kaldu instan rasa ayam atau daging secukupnya\n - garam dapur secukupnya\n - merica secukupnya\n - 150 ml air panas",
        "-125 gram tepung terigu\n - 100 ml susu cair\n - 10 keping biskuit oreo\n - 1 butir telur\n - 1 sdm gula halus\n - minyak goreng secukupnya",
        )

    private val reseps = arrayOf(
        "-Siapkan semua bahan-bahan\n -Haluskan bawang putih dan tumis hingga harum, sisihkan\n -Panaskan sedikit minyak di penggorengan\n -Pecahkan telur dan masak dengan di orak-arik\n -Masukan nasi\n -Tambahkan tumisan bawang putih, kecap asin, minyak wijen, kecap asin, garam, lada, dan irisan daun bawang.\n -Aduk terus hingga bumbu merata\n -Masukan sayuran seperti sawi dan kol\n -Campur dan aduk terus hingga sayuran matang\n -Jika sudah dinginkan terlebih dahulu di piring\n -Masukkan nasi goreng kedalam cup-cup\n -Kreasikan sesuai selera, bisa ditambah dengan telur yang digoreng atau potongan sosis atau keju.\n -Nasi goreng cup siap dijual",
        "-Cincang dada ayam dan blender hingga halus\n -Cincang kasar daun bawang\n -Ulek atau blender bawang putih dan bawang goreng\n -Siapkan wadah\n -Masukan daging ayam kedalam wadah\n -Tambahkan bawang putih dan bwang goreng yang telah dihaluskan dan aduk\n -Masukan tepung terigu, tepung kanji, daun bawang dan semua bumbu-bumbu seperti garam, gula, lada bubuk, dan kaldu bubuk.\n -Uleni hingga semua bahan tercampur\n -Kepal kepal adonan sempol dan tusuk menggunakan tusuk sate\n -Terus lakukan hingga adonan habis\n -Rendam ke dalam air yang mendidih hingga mengembang\n -Jika sudah, angkat dan tiriskan\n -Siapkan wadah untuk mengocok telur dan garam -Balurkan sempol dengan adonan telur\n -Panaskan minyak\n -Goreng sempol hingga matang",
        "-Siapkan wadah atau mangkuk berukuran besar\n -Kocok telur dan gula hingga bercampur\n -Masukan tepung terigu, fermipan, baking powder, dan gara,\n -Campurkan dan terus diaduk\n -Tambahkan air sedikit demi sedikit\n -Jika sudah tercampur, diamkan sejenak selama 1-2 jam\n -Siapkan cetakan martabak mini dan panaskan\n -Olesi cetakan menggunakan mentega\n -Tuangkan adonan ke cetakan\n -Tekan bagian atasnya agar mendapatkan pinggiran martabak\n -Jika adonan mulai terlihat berlubang tambahkan gula\n -Tutup sebentar -Angkat saat martabak telah matang -Tambahkan taburan coklat dan keju -Gunakan mika untuk mengemas martabak mini",
        "-Siapkan bahan-bahan untuk membuat kulit kebab\n -Campurkan semua bahan didalam wadah\n -Uleni hingga kalis\n -Sisihkan dan diamkan selama 30 menit\n -Buat adonan berbentuk bola-bola, usahakan ukurannya sama\n -Giling adonan yang sudah dibulat-bulat\n -Panaskan teflon dengan api sedang\n -Panggang kulit kebab\n -Kulit kebab siap digunakan\n -Selanjutnya tata daging ayam, sosis, selada secukupnya di atas kulit kebab\n -Tambahkan saus tomat dan mayonaise\n -Gulung kebab dan siap dikemas",
        "-Tumis semua bumbu-bumbu seperti bawang putih, bawang bombai, gula, dan garam\n -Masukan makroni yang sudah direbus dan paprika\n -Aduk hingga merata, sisihkan\n -Kocok telur dan masukan bahan-bahan yang sudah ditumis tadi kedalam satu wadah.\n -Bagi adonan kedalam cup cup\n -Selanjutnya buat saus putih dengan melelehkan mentega dan campurkan semua bahan seperti keju, suus cairm tepung terigu, gula, dan garam.\n -Masukan saus putih ke dalam cup makaroni\n -Berikan taburan keju parut\n -Oven dengan api sedang\n -Macaroni schotel siap dipasarkan",
        "-Siapkan wadah dan kocok telur dengan garam, lada, dan kaldu bubuk\n -Masukan kocokan telur kedalam botol saus atau botol apa saja yang memiliki lubang kecil dibagian atas.\n -Panaskan minyak goreng dengan api sedang\n -Sebelum menggoreng, pastikan minyak sudah benar-benar panaskan\n -Tuangkan adonan dengnan posisi botol lebih tinggi dari permukaan minyak\n -Tuangkan dengan berputar cepat dan merata ke bagian minyak panaskan\n -Masukan tusuk sate dan gulung perlahan hingga telur menempel\n -Pastikan telur sudah menggulung dan menempel pada tusuk sate\n -Tempelkan sesaat telur gulungnya ke pinggir penggorengan\n -Angkat dan tiriskan",
        "-Haluskan bawang putih, garam, dan merica\n -Cincang daun bawang\n -Campurkan semua bahan dalam satu wadah\n -Tambahkan sedikit demi sedikit air sambil diaduk\n -Uleni hingga adonan kalis\n -Lumuri tangan dan wadah lain dengan tepung\n -Buat adonan cilok dan masukan dalam wadah yang telah dipersiapkan\n -Didihkan air didalam panci\n -Masukan cilok kedalam air mendidih\n -Diamkan hingga cilok mengambang dipermukaan air\n -Angkat dan tiriskan\n -Siram dengan saus sesuai selera",
        "-Campurkan semua bahan untuk kulit dalam satu wadah, uleni hingga kalis\n -Lumuri dengan sedikit minyak goreng\n -Bagi adonan dengan membentuknya bulat-bulat.\n -Selanjutnya siapkan isian dumpling yakni daging ayam, wortel, sawi putih, jamur tiram, telur dan semua bumbu-bumbu\n -Campur dan aduk hingga merata\n -Selanjutnya buat dumplingnya dengan cara mengambil adonan kulit dan meratakannya hingga pipih\n -Masukan satu sendok isian diatas kulit dumpling\n -Lipat kulit dengan melipat salah satu sisi kemudian digulung hingga menyerupai gambar\n -Lakukan hingga seluruh adonan habis\n -Masukan dumpling kedalam air mendidih\n -Tunggu hingga dumpling mengambang dipermukaan air\n -Angkat lalu tiriskan\n -Diamkan sejenak sebelum digoreng\n -Siapkan penggorengan dan minyak\n -Goreng dumpling dengan api sedang\n -Jika sudah matang, tiriskan dan kemasan\n -Lebih enak jika disajikan dengan cocolan sambal atau saus",
        "-Rebus kentang dan wortel\n -Haluskan bawang merah, bawang putih, dan cabai menggunakan blender.\n -Potong dadu wortel dan kentang\n -Tumis bumbu dengan sedikit minyak goreng\n -Masukan daging ayam cincang, masak hingga mulai berwarna kekuningan\n -Tambahkan kentang, wortel, dan daun seledri.\n -Bumbui dengan garam, gula, dan bubuk kari. Koreksi rasa\n -Aduk hingga matang, sisihkan\n -Ambil satu lembar kulit lumpia\n -Berikan isian diatasnya\n -Lipat kedua sisi kulit, gulung kebawah, dan bentuk menyerupai segitiga\n -Rekatkan dengan putih telur\n -Goreng samosa hingga coklat keemasan\n -Angkat dan tiriskan",
        "-Campurkan tepung terigu, tepung tapioka dan tepung beras dalam satu wadah\n -Tambahkan garam, gula dan soda kue, aduk hingga rata.\n -Pecahkan telur dalam wadah lain\n -Tambahkan vanili dan susu cair\n -Kocok menggunakan mixer, atau bisa juga menggunakan whisk atau sendok biasa\n -Panaskan teflon dengan api kecil\n -Tuangkan adonan ke teflon, sekitar satu sendok sayur\n -Pastikan adonan bisa sesuai dengan permukaan teflon\n -Tambahkan irisan pisang, coklat tabur, dan parutan keju diatasnya\n -Jika sudah matang bisa langsung diangkat\n -Bisa juga dilipat terlebiuh dahulu sebelum diangkat\n -Leker pisang keju siap dipasarkana",
        "-Saring tepung terigu agar mendapatkan adonan yang halus\n -Campurkan tepung terigu, seledri, bumbu-bumbu, dan air secukupnya\n -Aduk hingga rata\n -Panaskan cetakan takoyaki dan olesi dengan minyak goreng\n -Masukkan adonan ke cetakan\n -Berikan isi takoyaki diatasnya, yakni ayam rebus dan sosis secukupnya\n -Jika mulai kering putar adonan hingga berbentuk bulat\n -Gunakan tusuk sate atau sumpit untuk memutarnya\n -Bolak balik kembali takoyaki hingga minyak mulai mengering\n -Tiriskan dan susun diwadah mika yang sudah dilapisi kertas minyak\n -Tambahkan saus tomat dan mayonaise",
        "-Campurkan fermipan, gula, dan susu dan aduk\n -Diamkan selama 15 menit hingga mengembang\n -Tambahkan tepung terigu, mentega, dan garam\n -Uleni hingga kalis, diamkan selama 30 menit\n -Bentuk adonan menjadi bola bola sama rata, tidak perlu diberi lubang karena nanti akan ditusuk dengan tusuk sate\n -Panaskan minyak goreng dengan api kecil\n -Goreng adonan donat dan angkat\n -Taburi dan hias dengan topping sesuai selera\n -Tusuk 3 donat menggunakan satu tusuk sate\n -Donat sate siap dijual",
        "-Masukkan telur ke dalam wadah, tambahkan vanili dan gula pasir. Kocok sebentar menggunakan tangan atau mixer.\n -Tambahkan margarin yang telah dicairkan dan air. Kocok kembali sampai tercampur rata.\n -Sambil tetap dikocok, masukkan tepung terigu sedikit demi sedikit. Kocok hingga rata.\n -Tambahkan baking powder dan rata. Kocok kembali.\n -Bagi adonan untuk diolah menjadi empat varian rasa.\n -Masukkan masing-masing adonan dengan varian rasa yang berbeda. Satu diberi bubuk matcha, satu diberi bubuk taro, satu diberi coklat bubuk, pewarna, dan cuka apel. Sedangkan untuk yang terakhir, biarkan tanpa tambahan.\n -Panaskan cetakan dan olesi dengan margarin.\n -Cetak masing-masing varian rasa.\n -Beri topping sesuai selera.\n -Tutup cetakan jika kamu ingin kue cubit matang dengan sempurna.\n -Matikan api, angkat kemudian hidangkan.",
        "-Panaskan minyak dalam wajan, lalu masak tahu sampai matang atau keluar lapisan coklat kulitnya dan tiriskan.\n -Ambil wadah lalu masukkan tepung terigu bersama dengan tepung aci, kaldu bubuk, bawang putih, garam dapur, merica halus, dan irisan daun bawang.\n -Aduk semua bahan tersebut sampai rata hingga menjadi adonan untuk isi tahu walik.\n -Setelah rata, tuang air panas sedikit demi sedikit sambil diaduk sampai adonan terasa pas.\n -Setelah adonan isi siap, kemudian belah tahu yang telah matang menjadi 2 bagian bentuk segitiga.\n -Keluarkan isi tahunya, lalu buang atau campur bersama dengan adonan aci tadi.\n -Balik sehingga kulitnya berada di dalam lalu isi dengan adonan sesuai selera.\n -Siapkan wajan berisi minyak agak banyak lalu masukkan tahu yang telah diisi setelah minyak benar-benar panas.\n -Balik dan goreng hingga matang dengan api sedang supaya matang sampai di dalamnya.\n -Setelah matang angkat dan tiriskan.\n -Tahu walik siap untuk disajikan.",
        "-Campurkan tepung terigu, gula halus, susu cair, dan telur dalam satu wadah, lalu aduk hingga kental.\n -Tambahkan oreo ke dalam adonan tersebut hingga adonan menutupi permukaan oreo.\n -Lalu, panaskan minyak goreng dan goreng adonan yang berisi oreo tersebut sampai berwarna kuning kecoklatan.\n -Angkat lalu tiriskan.\n -Oreo goreng siap untuk dinikmati.",

    )

    private val kesimpulans = arrayOf(
        "Sentuhan Magis Nasi Goreng dalam Satu Cup! Cicipi Nasi Goreng Cup kami yang lezat, praktis, dan selalu siap menggugah selera Anda. Dengan campuran bumbu rahasia dan kualitas terbaik, setiap suapannya akan membawa Anda dalam perjalanan rasa yang tiada tara. Hadirkan kelezatan nasi goreng favorit Anda dalam sekejap, di mana pun Anda berada. Nasi Goreng Cup - Hidangan Anda yang Selalu Siap dalam Cup!",
        "Kelezatan Sempol Ayam yang Bikin Ketagihan! Rasakan gurihnya ayam fillet berkualitas tinggi yang dibalut dengan tepung renyah, menghadirkan cita rasa yang tak terlupakan dalam setiap gigitan. Sempol Ayam kami adalah camilan sempurna untuk melengkapi momen-momen istimewa Anda. Kami menggabungkan resep tradisional dengan sentuhan modern, sehingga setiap hapannya memberikan pengalaman kuliner yang istimewa. Segera nikmati Sempol Ayam, camilan favorit yang akan membuat Anda selalu ingin kembali!",
        "Kelezatan dalam Genggaman! Nikmati kenikmatan gurih dan manis Martabak Mini kami, yang siap memanjakan lidah Anda. Dengan adonan yang lembut dan isian yang melimpah, setiap potongan Martabak Mini adalah perpaduan sempurna antara tekstur yang renyah dan rasa yang luar biasa. Kami menghadirkan rasa autentik dalam ukuran mini yang praktis. Sajikan Martabak Mini dalam berbagai pilihan rasa yang menggugah selera. Jadikan setiap saat istimewa dengan Martabak Mini kami yang lezat!",
        "Sensasi Timur Tengah dalam Setiap Gigitan! Temukan kelezatan rempah-rempah yang memikat dan daging berkualitas tinggi yang dipanggang sempurna dalam setiap sajian Kebab kami. Kami memadukan rasa autentik Timur Tengah dengan sentuhan modern untuk menciptakan pengalaman kuliner yang tak terlupakan. Dengan pilihan isian yang beragam, dari daging sapi hingga ayam yang lezat, setiap gigitan Kebab adalah perjalanan rasa yang menggugah selera. Sajikan Kebab sebagai hidangan utama atau camilan favorit Anda. Rasakan cita rasa dunia dalam setiap gigitan Kebab kami!",
        "Kelezatan Bergizi yang Menyehatkan! Cicipi campuran lezat antara macaroni lembut, saus krim gurih, dan beragam bahan berkualitas tinggi dalam setiap suapan Macaroni Schotel kami. Hidangan yang begitu menggugah selera ini memberikan sensasi kenyamanan dan rasa yang memanjakan lidah Anda. Kami menghadirkan cita rasa yang autentik dengan sentuhan modern, sehingga setiap potongannya memberikan kenikmatan dan nutrisi yang seimbang. Sajikan Macaroni Schotel sebagai hidangan istimewa untuk keluarga Anda. Rasakan nikmatnya Macaroni Schotel kami yang begitu istimewa!",
        "Kelezatan yang Digulung dalam Setiap Gigitan! Nikmati kombinasi lezat antara telur yang lembut dan bahan isi yang melimpah dalam setiap gigitan Telor Gulung kami. Dengan rasa yang khas dan penyajian yang praktis, setiap gulungan telur adalah camilan yang sempurna untuk dinikmati kapan saja. Kami menghadirkan variasi isi yang beragam, dari sayuran segar hingga daging gurih, sehingga setiap Telor Gulung adalah pengalaman rasa yang tak terlupakan. Sajikan sebagai camilan atau hidangan ringan, dan rasakan kenikmatan Telor Gulung kami yang menggugah selera!",
        "Camilan Gurih yang Bikin Ketagihan! Rasakan sensasi unik dari Cilok kami, camilan tradisional yang lezat dan menggugah selera. Dibuat dari campuran tepung tapioka yang lembut dan daging ayam berkualitas tinggi, setiap Cilok adalah potongan kenikmatan yang sempurna untuk mengganjal lapar Anda. Kami menghadirkan rasa otentik dalam setiap gigitan dengan saus kacang yang khas. Sajikan Cilok sebagai camilan istimewa atau hidangan pembuka yang menggugah selera. Nikmati kelezatan Cilok, dan Anda pasti ingin mencicipinya lagi dan lagi!",
        "Kelezatan dalam Balutan Kulit Halus! Telusuri rasa autentik Dumpling Ayam kami, hidangan klasik yang begitu lezat dan menggugah selera. Dibuat dengan cermat, setiap Dumpling adalah perpaduan sempurna antara daging ayam berkualitas tinggi dan bumbu-bumbu yang khas. Kami menghadirkan rasa tradisional dalam kulit yang lembut dan kenyal, memberikan pengalaman kuliner yang tak terlupakan. Sajikan Dumpling Ayam sebagai hidangan pembuka yang istimewa atau tambahkan ke dalam sup kesukaan Anda. Setiap gigitan Dumpling Ayam adalah perjalanan rasa yang memuaskan.",
        "Kelezatan India dalam Setiap Lipatan! Nikmati kelezatan gurih dan renyah dari Samose, camilan klasik India yang begitu memikat selera. Kami menghadirkan pengalaman kuliner India otentik dengan kulit yang digoreng sempurna dan isian yang melimpah. Setiap gigitan Samose adalah perpaduan harmonis dari rempah-rempah, kentang, sayuran, dan daging, menciptakan ledakan rasa yang tak terlupakan. Sajikan Samose sebagai camilan istimewa atau hidangan pembuka yang selalu diingat dalam acara Anda. Jelajahi cita rasa India dalam setiap lipatan Samose kami!",
        "Leker Pisang Keju: Kelezatan Unik yang Memanjakan Lidah! Cicipi perpaduan yang menarik antara manisnya pisang matang dan gurihnya keju dalam setiap gigitan Leker Pisang Keju kami. Hidangan istimewa ini menghadirkan sensasi rasa yang unik dan menggugah selera. Kami menggoreng Leker dengan sempurna sehingga kulitnya menjadi renyah dan isian pisang keju yang lezat terasa meleleh di dalam mulut Anda. Sajikan sebagai camilan spesial atau makanan penutup yang sempurna. Leker Pisang Keju, sajian yang memadukan manis dan gurih dalam satu kesempurnaan rasanya!",
        "Kelezatan Jepang dalam Bola-bola Gurih! Nikmati sentuhan khas Jepang dengan setiap gigitan Takoyaki kami. Bola-bola gurih yang digoreng sempurna ini menghadirkan cita rasa otentik dengan isian potongan gurita yang lezat. Ditaburi saus takoyaki yang khas dan rempah-rempah, setiap Takoyaki adalah perpaduan rasa yang luar biasa. Sajikan sebagai camilan favorit di festival makanan atau sebagai hidangan ringan yang menggugah selera. Takoyaki, hidangan yang memikat lidah dengan rasa autentik Jepang!",
        "Kelezatan Donat yang Diubah dengan Sentuhan Khas! Temukan inovasi yang mengagumkan dalam setiap gigitan Donat Sate kami. Kami menghadirkan donat yang lembut dan empuk, dihiasi dengan saus kacang gurih dan potongan daging sate yang menggugah selera. Setiap gigitan adalah perpaduan unik antara manis, gurih, dan pedas, menciptakan sensasi rasa yang tak terlupakan. Donat Sate kami cocok sebagai camilan istimewa di setiap acara atau sebagai hidangan penutup yang menggugah selera. Rasakan kelezatan Donat Sate, dan Anda pasti ingin kembali untuk lebih banyak lagi!",
        "Kelezatan Manis dalam Setiap Cubitan! Nikmati manisnya Kue Cubit kami, camilan klasik yang selalu menghadirkan kebahagiaan dalam setiap cubitan. Dengan tekstur yang lembut dan cita rasa yang menggugah selera, setiap gigitan Kue Cubit adalah perpaduan yang sempurna antara manisnya kue dan aroma vanilla yang lezat. Kami menyajikan Kue Cubit dalam berbagai pilihan topping, dari cokelat leleh hingga meses warna-warni. Sajikan sebagai camilan favorit di setiap acara atau sebagai makanan penutup yang manis. Cubit Kue Cubit kami dan nikmati kelezatan manis dalam setiap cubitan!",
        "Sensasi Kuliner yang Luar Biasa! Nikmati kombinasi istimewa antara tahu lembut dan kulit aci yang renyah dalam setiap hidangan Tahu Walik Aci kami. Kami menggulung tahu dalam kulit aci yang digoreng sempurna, menciptakan kelezatan yang tak terlupakan. Dengan saus spesial yang khas dan bumbu yang menggugah selera, setiap gigitan Tahu Walik Aci adalah perpaduan rasa yang unik. Sajikan sebagai camilan spesial atau hidangan pembuka yang selalu diingat. Temukan sensasi kuliner yang luar biasa dengan Tahu Walik Aci kami!",
        "Manisnya Oreo yang Dalam Setiap Gigitan! Rasakan transformasi ajaib Oreo dalam setiap gigitan Oreo Goreng kami. Kami menggoreng Oreo hingga kulitnya menjadi renyah dan karamel, sementara cokelat dalamnya tetap lembut. Hasilnya adalah kombinasi sempurna antara manisnya Oreo, tekstur renyah, dan cita rasa karamel yang memukau. Sajikan sebagai makanan penutup yang istimewa atau camilan gurih di kala ingin memanjakan diri. Oreo Goreng, sensasi manis yang memikat selera Anda!",
    )

    private val imgs = arrayOf(
        R.drawable.nasi_goreng_cup,
        R.drawable.sempol_ayam,
        R.drawable.martabak_mini,
        R.drawable.kebab,
        R.drawable.macaroni_schotel,
        R.drawable.telor_gulung,
        R.drawable.cilok,
        R.drawable.dumpling_ayam,
        R.drawable.samosa,
        R.drawable.leker_pisang_keju,
        R.drawable.takoyaki,
        R.drawable.donat_sate,
        R.drawable.kue,
        R.drawable.tahu_walik_acik,
        R.drawable.oreo_goreng,
    )


    fun listdesk(): List<resep>{
        val dataResep = mutableListOf<resep>()
        for (index in namaResep.indices){
            val data = resep(
                namaResep[index],
                bahanResep[index],
                reseps [index],
                kesimpulans [index],
                imgs [index]
            )
            dataResep.add(data)
        }
        return dataResep
    }

}
